/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.parser;

import minipython.node.*;
import minipython.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    public void caseTTab(TTab node)
    {
        index = 0;
    }

    public void caseTPlus(TPlus node)
    {
        index = 1;
    }

    public void caseTMinus(TMinus node)
    {
        index = 2;
    }

    public void caseTMult(TMult node)
    {
        index = 3;
    }

    public void caseTDiv(TDiv node)
    {
        index = 4;
    }

    public void caseTEq(TEq node)
    {
        index = 5;
    }

    public void caseTLPar(TLPar node)
    {
        index = 6;
    }

    public void caseTRPar(TRPar node)
    {
        index = 7;
    }

    public void caseTComma(TComma node)
    {
        index = 8;
    }

    public void caseTIf(TIf node)
    {
        index = 9;
    }

    public void caseTPrint(TPrint node)
    {
        index = 10;
    }

    public void caseTLess(TLess node)
    {
        index = 11;
    }

    public void caseTGreat(TGreat node)
    {
        index = 12;
    }

    public void caseTTrue(TTrue node)
    {
        index = 13;
    }

    public void caseTSemi(TSemi node)
    {
        index = 14;
    }

    public void caseTFalse(TFalse node)
    {
        index = 15;
    }

    public void caseTElse(TElse node)
    {
        index = 16;
    }

    public void caseTQuote(TQuote node)
    {
        index = 17;
    }

    public void caseTNumber(TNumber node)
    {
        index = 18;
    }

    public void caseTId(TId node)
    {
        index = 19;
    }

    public void caseEOF(EOF node)
    {
        index = 20;
    }
}
